FROM almalinux:9
MAINTAINER Rajesh rajeshkalavapalli@gmail.com   
RUN echo "my first exicute 1"
RUN echo "my first exicute 2"
RUN echo "my first exicute 3"
RUN echo "my first exicute 4"
CMD  echo "my cmd exicute 1"